# Generated by Django 4.1 on 2023-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PokemonApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
