# Generated by Django 4.1 on 2023-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PokemonApp", "0002_alter_pokemon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="region", name="url_img", field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="tipo2",
            field=models.CharField(default="No tiene", max_length=40),
        ),
    ]
