# Generated by Django 4.1 on 2023-03-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PokemonApp", "0004_alter_pokemon_tipo2"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="nombre",
            field=models.CharField(default=None, max_length=40),
        ),
    ]
