# Generated by Django 4.1 on 2023-03-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PokemonApp", "0007_alter_region_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region", name="url_img", field=models.URLField(),
        ),
    ]
