# Generated by Django 4.1.7 on 2023-03-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0008_alter_region_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo2',
            field=models.CharField(max_length=40),
        ),
    ]
