# Generated by Django 4.1.7 on 2023-03-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0009_alter_pokemon_tipo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
