# Generated by Django 4.1.7 on 2023-03-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonApp', '0011_pokemon_numero_alter_pokemon_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='numero',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
